AWSTemplateFormatVersion: '2010-09-09'
Description: 'ForwardsFlow Platform - Additional Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  MPESAConsumerKey:
    Type: String
    NoEcho: true
    Description: MPESA Daraja API Consumer Key

  MPESAConsumerSecret:
    Type: String
    NoEcho: true
    Description: MPESA Daraja API Consumer Secret

Resources:
  # S3 Bucket for Document Storage
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'forwardsflow-documents-${EnvironmentName}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # CloudWatch Log Group
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/forwardsflow/${EnvironmentName}'
      RetentionInDays: 30

  # SNS Topic for Notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'forwardsflow-notifications-${EnvironmentName}'
      DisplayName: ForwardsFlow Notifications
      Subscription:
        - Endpoint: admin@forwardsflow.com
          Protocol: email

  # Secrets Manager for API Keys
  APISecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'forwardsflow/${EnvironmentName}/api-keys'
      Description: API keys and secrets for ForwardsFlow
      SecretString: !Sub |
        {
          "mpesa_consumer_key": "${MPESAConsumerKey}",
          "mpesa_consumer_secret": "${MPESAConsumerSecret}",
          "twilio_account_sid": "",
          "twilio_auth_token": "",
          "stripe_secret_key": ""
        }

  # EventBridge Rule for Daily Reports
  DailyReportRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'forwardsflow-daily-report-${EnvironmentName}'
      Description: Trigger daily report generation
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DailyReportFunction.Arn
          Id: DailyReportTarget

  # Lambda Function for Daily Reports
  DailyReportFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'forwardsflow-daily-report-${EnvironmentName}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          SNS_TOPIC_ARN: !Ref NotificationTopic
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log('Generating daily report...');
            // Report generation logic
            return { statusCode: 200 };
          };

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'forwardsflow-lambda-role-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${DocumentsBucket.Arn}/*'
        - PolicyName: SNSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref NotificationTopic
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref APISecretsManager

  # Permission for EventBridge to invoke Lambda
  DailyReportPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DailyReportFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyReportRule.Arn

  # CloudWatch Dashboard
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub 'ForwardsFlow-${EnvironmentName}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum"}],
                  [".", "Errors", {"stat": "Sum"}],
                  [".", "Duration", {"stat": "Average"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Lambda Metrics"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", {"stat": "Sum"}],
                  [".", "ConsumedWriteCapacityUnits", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "DynamoDB Capacity"
              }
            }
          ]
        }

  # CloudWatch Alarm for Lambda Errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'forwardsflow-lambda-errors-${EnvironmentName}'
      AlarmDescription: Alert when Lambda error rate is high
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref NotificationTopic

  # WAF Web ACL for API Protection
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub 'forwardsflow-waf-${EnvironmentName}'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: ForwardsFlowWebACL

Outputs:
  DocumentsBucketName:
    Description: S3 Bucket for Documents
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${AWS::StackName}-DocumentsBucket'

  NotificationTopicArn:
    Description: SNS Topic ARN for Notifications
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  SecretsManagerArn:
    Description: Secrets Manager ARN
    Value: !Ref APISecretsManager
    Export:
      Name: !Sub '${AWS::StackName}-APISecrets'

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=ForwardsFlow-${EnvironmentName}'
